### ISSUE TITLE
Cannot install the plugin

### ISSUE THREAD

**Issue by Henrique-Batista** [miguelanruiz/glpi-meshcentral#1]
Hi, i have tested the default glpi plugin install in 2 different servers, but no success, can you help me? Do not showing the plugin in the Web UI.

**Comment by rallisf1** [comment]
This plug-in is a left-over from the official meshcentral implementation which, frankly is half-baked and outdated. I tried updating it but I'm stuck as I've never written code for glpi before. I will open a new issue here in case miguel wants to help.
